/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        "Sora-Thin": ["Sora-Thin"],
        "Sora-Extralight": ["Sora-Extralight"],
        "Sora-Light": ["Sora-Light"],
        "Sora-Regular": ["Sora-Regular"],
        "Sora-Medium": ["Sora-Medium"],
        "Sora-SemiBold": ["Sora-SemiBold"],
        "Sora-Bold": ["Sora-Bold"],
        "Sora-Extrabold": ["Sora-Extrabold"],
        "Sora-Black": ["Sora-Black"],
        "Inter-Thin": ["Inter-Thin"],
        "Inter-Extralight": ["Inter-Extralight"],
        "Inter-Light": ["Inter-Light"],
        "Inter-Regular": ["Inter-Regular"],
        "Inter-Medium": ["Inter-Medium"],
        "Inter-Bold": ["Inter-Bold"],
        "Inter-Extrabold": ["Inter-Extrabold"],
        "Inter-Black": ["Inter-Black"],
        "CabinetGrotesk-Thin": ["CabinetGrotesk-Thin"],
        "CabinetGrotesk-Extralight": ["CabinetGrotesk-Extralight"],
        "CabinetGrotesk-Light": ["CabinetGrotesk-Light"],
        "CabinetGrotesk-Regular": ["CabinetGrotesk-Regular"],
        "CabinetGrotesk-Medium": ["CabinetGrotesk-Medium"],
        "CabinetGrotesk-Bold": ["CabinetGrotesk-Bold"],
        "CabinetGrotesk-Extrabold": ["CabinetGrotesk-Extrabold"],
        "CabinetGrotesk-Black": ["CabinetGrotesk-Black"],
      },
      colors: {
        brandColor: "#E1AE3C",
        lightGreen: "#c2f19e",
        SideNav: "#f4f8fa",
        lighterGreen: "#E1FCCF",
        DirtyFreen: "#EEEEEE",
        grey: "#C3B9B9",
        darkBg: "#212121",
        inputFieldBg: "#F7F9FB",
        greyText: "#AFAFAF",
        placeholder: "#C3B9B9",
        lightYellow: "#FFB800",
        error: "#C93636",
        lightRed: "#C93636",
        darkGrey: "#A6B29D",
        disabled: "#A6B29D",
        formDisabledBg: "#A6B29D",
        pendingStatus: "#FFB800"
      },
    },
  },
  plugins: [],
}